version: 0.2
phases:
  pre_build:
    commands:
      - echo "Entered in prebuild phase";
  build:
    commands:
      - echo "Entered in build phase"
  post_build:
    commands:
      - echo "Enteredin post-build phase"
artifacts:
  files:
    - index.php
    - style.css
    - about-us.php
    - cancelorder.php
    - cart.php
    - category-details.php
    - change-password.php
    - contact-us.php
    - forgot-password.php
    - logout.php
    - my-order.php
    - my-order1.php
    - order-detail.php
    - products.php
    - profile.php
    - signup.php
    - single-product-detail.php
    - trackorder.php
    - '**/*'
